### ISSUE TITLE
Unable to set tabWidth

### ISSUE THREAD

**Issue by joshagudo** [prettier/prettier-atom#241]
Getting an error trying to set the tab width to 2.

![screen shot 2017-07-27 at 5 35 09 pm](https://user-images.githubusercontent.com/6194037/28659266-323e0910-72f2-11e7-84c1-4b429d117fc0.png)

![screen shot 2017-07-27 at 5 34 59 pm](https://user-images.githubusercontent.com/6194037/28659269-36926b46-72f2-11e7-873a-96efc27c4d25.png)

Atom version =  1.18.0
prettier-atom = 0.37.0

**Comment by joshagudo** [comment]
@robwise manually updating it from `"2"` still doesn't seem to apply any change (reverts back to editor tabWidth). I've ensured that when manually formatting a file the following exists in the configuration file: `tabWidth: 2`

**Comment by robwise** [comment]
Can you copy and paste everything under `"prettier-atom"` in your config.cson?

**Comment by joshagudo** [comment]
```
"prettier-atom":
    formatOnSaveOptions:
      enabled: true
    prettierOptions:
      jsxBracketSameLine: true
      useTabs: true
      tabWidth: 2
```
