### ISSUE TITLE
Settings doesn't works after the last update.

### ISSUE THREAD

**Issue by DavidTorrijos** [prettier/prettier-atom#450]
Hey there!
I having some problems with your pluggin after the last update. I think it's ignoring the orders at Atom config.cson, for example:

I have enabled single quote option and the plugin sets double quote when I save. It writing ";" at final of lines and probably another things more, because I see my file a little bit difference than before the update. 

Is like the plugin is ignoring the config. This is a snnipet of my config.cson:

``` 
"prettier-atom":
    formatOnSaveOptions:
      enabled: true
      showInStatusBar: true
    prettierOptions:
      jsxBracketSameLine: true
      semi: false
      singleQuote: true
```

I didn't change my settings, I don't know why the plugin change the files...
Thank you!
