### ISSUE TITLE
unable to set tabWidth

### ISSUE THREAD

**Issue by AurelReb** [prettier/prettier-atom#504]
Hi,
There is no way to change the tab width. 
- changing in editor settings  do nothing
- changing in config.cson do nothing :  
```
"prettier-atom":
    formatOnSaveOptions:
      enabled: true
    prettierOptions:
      jsxBracketSameLine: true
      tabWidth: 4
      useTabs: true
```
- no option available to change it in the package settings

How can I change default tabWidth (2) to 4?
Thank you
